### ISSUE TITLE
Set upper limit to consecutive reconnections

### ISSUE THREAD

**Issue by mirka** [Automattic/lasagna.js#182]
In a situation where the websocket server connects and then immediately closes the connection for some reason, the Lasagna client will immediately try to reconnect, causing an endless loop of retries.

p1641480245001100-slack-C010KDAPG49

**Comment by hewsut** [comment]
Interesting, hm. `phoenix.js`, which underlies this lib, has an exponential backoff capped at 5 sec recurring by default:
 
https://github.com/phoenixframework/phoenix/blob/23d98fca8529c72d5adde2e650a64d11bed97fda/assets/js/phoenix/socket.js#L49

It's configurable and IIRC `lasagna.js` does pass params down -- or it could of course. So that maybe an avenue here.

I would expect a 5s recurring attempt to be just fine so I wonder if the funky reinit stuff we do for auth is breaking the exponential backoff that would normally happen.
